### PR TITLE
Extended the HumanMade branch into a universally usable plugin, maintaining backwards compatibility with previous versions.

### PR DESCRIPTION
**Pull request by AramZS**
At their upstream fork @dashaluna and @mattheu and the rest of the HumanMade team have done some excellent work extending the plugin, adding more significant checking, additional shortcode coverage, and building some useful additional functionality. 

Their forward repo is unfortunately neither backwards compatible nor clear of code for a particular client. This branch is almost all their work (significant props to them here), but I've stripped out the code that is not universally usable (that using custom plugins maintained by their client and client-specific auth and tracking codes) and added back in the filters required to assure backwards compatibility for developers who had already filtered the template file names for their own work. 

Finally I added in the code from pull request #37 addressing the issue of #34, which is needed for my implementation of this and I believe should be included going forward, as well as an additional filter to allow developers to filter any template file called by the internal function.

### CODE REVIEW

**Comment by AramZS** [comment]
Now tested, last step complete to assure full back-compat so that any devs using this plugin with the old version of the templates, external to the plugin, would not find themselves with crashed pages.

**Comment by dashaluna** [comment]
@AramZS great work :+1: 
Sorry for nitpicking, but I have noticed some [WP PHP Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/) issues. Do you want me to clean them up in a commit or add comments to this PR and you can do it? I don't mind either way, but would be great to fix them before merge :)

There are also some in PR #37

**Comment by dashaluna** [comment]
@AramZS also, I think you should add your name to contributors too :)

**Comment by AramZS** [comment]
Hey @dashaluna, I was afk on vacation last week and only saw this now. Thanks for your idea and to @whyisjake for adding my name! Are there any remaining coding standards problems or did @whyisjake fix them all? If there are some remaining, lets open up a new PR to clean it up.

**Comment by dashaluna** [comment]
@AramZS no worries. Yep, there are some still - I was hoping to fix it today/tomorrow and open a PR :) /cc @whyisjake

**Pull request merged**
