### PR TITLE
Fix coding standards

### PR DESCRIPTION
**Pull request by dashaluna**

### CODE REVIEW

**Comment by dashaluna** [comment]
@whyisjake fixed coding standards and couple of re-arrangements of properties for clarity. /cc @AramZS

**Comment by AramZS** [comment]
Awesome, thanks @dashaluna ! 

Ugh, I can't believe I misspelled compatibility >.<

**Comment by whyisjake** [comment]
Thanks so much @dashaluna and @AramZS. Going to merge this, and do a new release soon.

**Comment by dashaluna** [comment]
:+1: :)

**Pull request merged**
